# Generated by Django 5.1.4 on 2025-01-24 00:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthpersonnel',
            name='is_hidden',
        ),
        migrations.AlterField(
            model_name='administrator',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='healthpersonnel',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
