# Generated by Django 5.1.4 on 2025-01-16 11:49

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('notes', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
            ],
        ),
    ]
