# Generated by Django 5.1.4 on 2025-01-16 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('appointments', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='professional',
            field=models.ForeignKey(limit_choices_to={'role__in': ['DOCTOR', 'NURSE']},
                                    on_delete=django.db.models.deletion.CASCADE, to='users.healthpersonnel'),
        ),
    ]
