# Generated by Django 5.1.4 on 2025-01-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mrn', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('last_admission_date', models.DateTimeField()),
                ('age', models.PositiveIntegerField()),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=10)),
                ('blood_group_type',
                 models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=5)),
                ('rhesus_factor', models.CharField(choices=[('+', '+'), ('-', '-')], max_length=5)),
                ('blood_group', models.CharField(editable=False, max_length=5)),
                ('genotype',
                 models.CharField(choices=[('AA', 'AA'), ('AC', 'AC'), ('AS', 'AS'), ('SC', 'SC'), ('SS', 'SS')],
                                  max_length=5)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(max_length=15)),
                ('emergency_contact', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergies', models.JSONField(default=list)),
                ('chronic_conditions', models.JSONField(default=list)),
                ('previous_medications', models.JSONField(default=dict)),
                ('medical_history', models.JSONField()),
                ('family_history', models.JSONField(default=dict)),
                ('surgeries', models.JSONField(default=list)),
            ],
        ),
    ]
