# Generated by Django 5.1.4 on 2025-01-24 00:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativedata',
            name='relationship_status',
            field=models.CharField(blank=True,
                                   choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('DIVORCED', 'Divorced')],
                                   max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='administrativedata',
            name='suffix',
            field=models.CharField(blank=True, choices=[('MR', 'Mr'), ('MRS', 'Mrs'), ('MISS', 'MISS')], max_length=10,
                                   null=True),
        ),
        migrations.AlterField(
            model_name='administrativedata',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10),
        ),
    ]
