# Generated by Django 5.1.4 on 2025-01-16 11:49

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_scope', models.JSONField()),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('examination_ward', models.CharField(blank=True, max_length=100, null=True)),
                ('diagnosis', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('lab_result', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('prescription', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('date_diagnosed', models.DateTimeField(auto_now_add=True)),
                ('discharge_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid_id', models.CharField(max_length=24, unique=True)),
                ('insurance_info', models.JSONField()),
                ('is_active', models.BooleanField(default=True)),
                ('inactive_reason', django_ckeditor_5.fields.CKEditor5Field()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_hidden', models.BooleanField(default=False)),
            ],
        ),
    ]
