# Generated by Django 5.1.4 on 2025-01-16 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('records', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consent',
            name='granted_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.healthpersonnel'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='doctor_in_charge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_records',
                                    to='users.healthpersonnel'),
        ),
        migrations.AddField(
            model_name='patient',
            name='administrative_data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient',
                                       to='records.administrativedata'),
        ),
        migrations.AddField(
            model_name='patient',
            name='medical_data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient',
                                       to='records.medicaldata'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records',
                                    to='patients.patient'),
        ),
        migrations.AddField(
            model_name='consent',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
    ]
