# Generated by Django 5.1.5 on 2025-01-26 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_medicalrecord_is_opened'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='id',
        ),
        migrations.AlterField(
            model_name='patient',
            name='rfid_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
